//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketWebAPIBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillingTable()
        {
            this.BilledProductsTbs = new HashSet<BilledProductsTb>();
        }
    
        public int BillId { get; set; }
        public string CustomerId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BilledProductsTb> BilledProductsTbs { get; set; }
        public virtual CustomerTb CustomerTb { get; set; }
    }
}
