//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketWebAPIBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilledProductsTb
    {
        public int Id { get; set; }
        public Nullable<int> BillId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual BillingTable BillingTable { get; set; }
        public virtual ProductTb ProductTb { get; set; }
    }
}
