//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketWebAPIBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerTb()
        {
            this.BillingTables = new HashSet<BillingTable>();
        }
    
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public int Points { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingTable> BillingTables { get; set; }
    }
}
