//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketWebAPIBilling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTb()
        {
            this.BilledProductsTbs = new HashSet<BilledProductsTb>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public System.DateTime DateOfManufacture { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BilledProductsTb> BilledProductsTbs { get; set; }
    }
}
